### ISSUE TITLE
Tracking: Game-readiness of @react-three/rapier

### ISSUE THREAD

**Issue by hmans** [pmndrs/react-three-rapier#92]
I'm using this ticket as a high-level overview of things that are still missing for the library to be "game-ready". Please ready this merely as a tracking issue, not a wishlist. :-) I will be implementing some of these myself, and submitting them via PR.

### Must Have:

- [x] Clamp deltatime values to 1s max. (#85)
- [ ] Allow the user to use sensors. (#90?)

### Should Have:

- [x] Allow for per-collider collision callbacks. (#83)
- [x] Easy convex collider generation from any geometry, including loaded GLTFs.
- [ ] Allow the user to specify the `density` of colliders (or a default value on `RigidBody`.) (Rapier is nice in that it will automatically calculate the mass from the density and the volume of the colliders.)

### Nice to Have:

- [x] Easy to use physics debugger

**Comment by firtoz** [comment]
Made https://github.com/pmndrs/react-three-rapier/pull/101 before seeing this, I guess that will satisfy one of the checkboxes here? :D
